sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: wj

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t86zDoSdDdPyfadE81d
    access-key-secret: zmTems05zifZDgw6EqGRIFElVw861Z
    bucket-name: web-tlias-eijing
